from __future__ import annotations

TASK_MODE = "TASK_MODE"
VENT_MODE = "VENT_MODE"
BOUNDARY_MODE = "BOUNDARY_MODE"
AMBIGUITY_MODE = "AMBIGUITY_MODE"
EVIDENCE_AUDIT_MODE = "EVIDENCE_AUDIT_MODE"
SYSTEM_COMMAND_MODE = "SYSTEM_COMMAND_MODE"
DESTRUCTIVE_COMMAND_LOCK = "DESTRUCTIVE_COMMAND_LOCK"

ACTION_AUDIT_ONLY = "AUDIT_ONLY"
